<?php
// URL to UserProjectView plugin
define ( 'USERPROJECTVIEW_PLUGIN_URL', config_get_global( 'path' ) . 'plugins/' . plugin_get_current() . '/' );

// Path to UserProjectView plugin folder
define ( 'USERPROJECTVIEW_PLUGIN_URI', config_get_global( 'plugin_path' ) . plugin_get_current() . DIRECTORY_SEPARATOR );

// Path to UserProjectView core folder
define ( 'USERPROJECTVIEW_CORE_URI', USERPROJECTVIEW_PLUGIN_URI . 'core' . DIRECTORY_SEPARATOR );

define ( 'PLUGINS_USERPROJECTVIEW_THRESHOLD_LEVEL_DEFAULT', ADMINISTRATOR );

define ( 'PLUGINS_USERPROJECTVIEW_UNREACH_ISSUE_THRESHOLD_DEFAULT', 50 );

define ( 'PLUGINS_USERPROJECTVIEW_OLD_ISSUE_THRESHOLD_DEFAULT', 30 );

define ( 'PLUGINS_USERPROJECTVIEW_BACKGROUND_COLOR_DEFAULT', "#8b0000");

define ( 'PLUGINS_USERPROJECTVIEW_TEXT_COLOR_DEFAULT', "#000000");

define ( 'PLUGINS_USERPROJECTVIEW_COLUMN_AMOUNT_DEFAULT', 1);

define ( 'PLUGINS_USERPROJECTVIEW_ISSUE_THRESHOLD_DEFAULT', 5);
?>